main: me.joshiepillow.starwars.Main
name: starwars
version: 1.5.0
author: me
description: An Example plugin
api-version: 1.16
commands:
  forcepowers.grant:
    description: Grant force power
    usage: /<command> Username number
    permission: nope

  forcepowers.take:
    description: Take force power
    usage: /<command> Username number
    permission: nope

  forcepowers.item:
    description: Give forcepower ui block
    usage: /<command>

  forcepowers.save:
    description: Save data
      usage: /<command>
      permission: nope
depend: [LuckPerms, CustomItems]