main: me.joshiepillow.starwars.Main
name: starwars
version: 0.6.0
author: me
description: An Example plugin
api-version: 1.16
commands:
#  mycommand:
#    description: An example command
#    usage: /mycommand
#    permission: myplugin.mycommand
#    permission-message: You don't have the myplugin.mycommand permission.
#  players_at:
#    description: Check the number of players in a location
#    usage: /<command> [X-coord 1] [Y-coord 1] [X-coord 2] [Y-coord 2]
#  who_at:
#    description: Name of players in a world
#    usage: /<command>
#  summon_boss:
#    description: What do you think
#    usage: It's not that hard
  hunter.create:
    description: Create new hunter
    usage: /<command> Nickname [username]
    permission: bounty.use.create
  hunter.name:
    description: Get/Set name
    usage: /<command> Username [Nickname]
  hunter.bal:
    description: Get/Change balance
    usage: /<command> Username [change]
  hunter.list:
    description: List all hunters
    usage: /<command>
  hunter.buy:
    description: Buy a product
    usage: /<command> Username Product

  product.create:
    description: Create new product
    usage: /<command> name cost command
  product.cmd:
    description: Get/Set command
    usage: /<command> name [newCmd]
  product.name:
    description: Get/Set name
    usage: /<command> name [newName]
  product.cost:
    description: Get/Set cost
    usage: /<command> name [newName]
  product.list:
    description: List all products
    usage: /<command>

  test:
    description: test
    usage: /<command>
permissions:
   bounty.*:
        description: parent command node
        children:
            bounty.use: true
   bounty.use:
        description: allows users to use commands
        children:
            bounty.use.create: true            
